image: Visual Studio 2015

platform:
  - x86
  - x64

configuration: Release

build_script:
  - cmd: if "%platform%"=="x86" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - cmd: if "%platform%"=="x64" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmd: cmake -H. -B_build -G "%CMAKE_GENERATOR_NAME%"
  - cmd: cmake --build _build --config %configuration%
